### ISSUE TITLE
Should be pdf print friendly

### ISSUE THREAD

**Issue by cppcooper** [xriley/DevResume-Theme#2]
The theme is not easily printed to pdf, being intended for resumes it should be a consideration.

I've managed to make my fork pdf print friendly, but I am by no means a web developer. https://github.com/cppcooper/cppcooper.github.io

I basically came up with a hack [today] to create a print media duplicate of the main stylesheet with the necessary changes to make it printer friendly.

**Comment by xriley** [comment]
For anyone who needs a PDF version of the resume design you can download the free Sketch file on my website below: https://themes.3rdwavemedia.com/resources/sketch-template/devresume-sketch-sketch-resume-template-for-software-developers/

;)

**Comment by cppcooper** [comment]
Well not for anyone. Sketch is only available for macOS, and costs $99. So only for people with $99 to burn for a pdf version of their resume, or already use the tool and are a developer using Mac.

**Comment by xriley** [comment]
That’s true. Forgot it’s only for Mac...but Mac users can use it for free
for 30 days - https://www.sketch.com/try/
