### ISSUE TITLE
How to export my CV in pdf format? 

### ISSUE THREAD

**Issue by ambarja** [xriley/DevResume-Theme#5]
Hi @xriley , thanks a lot for sharing your template, in my opinion, is gorgeous.
My question is how to export this template in cv format? 
Thanks!

![Captura de pantalla de 2021-07-24 15-30-58](https://user-images.githubusercontent.com/23284899/126880425-8f2ca6ff-afe8-41a9-96ee-c32d169733b5.png)

**Comment by xriley** [comment]
> Re: My question is how to export this template in cv format?

Unfortunately that's not possible. 
However, you might find our Sketch template useful for creating a PDF CV - https://themes.3rdwavemedia.com/resources/sketch-template/devresume-sketch-sketch-resume-template-for-software-developers/
